### ISSUE TITLE
Rewrite progress.

### ISSUE THREAD

**Issue by mudlord** [mudlord/einweggerat#4]
**Todo**:
- [ ] Basic windowing (WTL)
- [ ] Basic C/C++ STL replacement
- [ ] Rendering (Vulkan/OGL)
- [ ] Sound (WASAPI+resampler)
- [ ] Input (Xinput/RawInput/DirectInput)
- [ ] Serialization for settings
- [ ] Libretro interaction
- [ ] Commandline support
- [ ] ROM browser

**Comment by mudlord** [comment]
Mostly worked on serialization this morning. Going to implement compression on the settings. Ideally would use something non human readable, but bleh. DEFLATE will be used for compression.

Serialization for config now is tons cleaner, removed some C baggage.

**Comment by mudlord** [comment]
Graphics need a rewrite to accommodate some of my very low end systems as well as others.

A factory based method needs to be done to implement:

    Vulkan
    OGL 4.6 with bindless/DSA
    Direct2D (should be fine for lower end systems even on Win7)

Maybe mini_al could be reimplemented for DirectSound and WASAPI handling. Maybe WASAPI is enough for Win7-11?

**Comment by mudlord** [comment]
Figured WASAPI alone should be fine. Providing its up to standard. Renderer is being rewritten.

**Comment by mudlord** [comment]
Rewrote into new classes.

D3D9 is done for pure 2D cores. Need to add Vulkan and D3D11 for hardware cores that use those.

**Comment by mudlord** [comment]
Started writing D3D11 hardware renderer.

D3D9 software rasterizer is complete.
